### ISSUE TITLE
Readme.MD - Dependency

### ISSUE THREAD

**Issue by Maskulinum** [ysph/g403-GUI-control#1]
Just trying:
sudo apt-get install libusb-1.0-dev
I got the message:
libusb-1.0-dev can't find.

Could
sudo apt-get install libusb-1.0-0-dev
the right one?

**Comment by ysph** [comment]
Hello!

Yes, this one is correct:
> sudo apt-get install libusb-1.0-0-dev

Thanks!
https://github.com/ysph/g403-GUI-control/commit/e715f4b4fcb482b414ac113e7f5ebaad566d5cfe
